version: '3.9'
name: content-auth-server
services:
  backend-app:
    build: ./backend
    container_name: auth-server
    ports:
      - "8080:8080"

  frontend-ui:
    build: ./frontend
    container_name: auth-page
    ports:
      - "9000:80"